### ISSUE TITLE
AdMob: Unable to initialize without Google Play Services

### ISSUE THREAD

**Issue by mrpuzzler** [firebase/firebase-cpp-sdk#127]
Under Android replace:

firebase::admob::Initialize(*app, kAdMobAppID);
with
firebase::admob::Initialize(GetJniEnv(), GetActivity(), kAdMobAppID);

and you get crash, as there is no such method on Android side.

**Comment by mrpuzzler** [comment]
Lol, after almost 1.5 year you still did not fix it, are you serious?

**Comment by DellaBitta** [comment]
Hi all,

We've since deprecated the AdMob SDK and have replaced it with the [Google Mobile Ads (GMA) SDK](https://firebase.google.com/docs/admob/cpp/admob-migration).  've just tested this and I was able to create an instance of the GMA SDK without Google Play Services. If you do encounter this issue still on the GMA SDK, then please open another ticket and we'll look into it further. Thank you!
