### ISSUE TITLE
ios - linking error

### ISSUE THREAD

**Issue by crazyhappygame** [firebase/firebase-cpp-sdk#19]
What library should be linked to fix below error?
xcode: 10.3
macos: 10.14.5

I would like to stay with command line and cmake and do not use CocoaPods and open xcode.

In documentation I see  "Integrate without CocoaPods"
https://firebase.google.com/docs/ios/setup#frameworks

This is my cmake:
```
# Add Firebase libraries to the target using the function from the SDK.
add_subdirectory(${EXTERNAL_DIR}/firebase_cpp_sdk bin/ EXCLUDE_FROM_ALL)

# The core Firebase library (firebase_app) is required to use any Firebase product,
# and it must always be listed last.
target_link_libraries(${PROJECT_NAME}
    firebase_analytics
    firebase_remote_config
    firebase_app)
```
Error:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIROptions", referenced from:
      objc-class-ref in firebase(app_ios_814e1620d4f88024cea4bade26623a67.o)
  "_OBJC_CLASS_$_FIRConfiguration", referenced from:
      objc-class-ref in firebase(log_ios_dd26aec5b8537064a4c15d38b58b4640.o)
  "_OBJC_CLASS_$_FIRRemoteConfigSettings", referenced from:
      objc-class-ref in firebase_remote_config(remote_config_ios_e6d2ed559f32c182ac8412737f5fb36a.o)
  "_OBJC_CLASS_$_FIRRemoteConfig", referenced from:
      objc-class-ref in firebase_remote_config(remote_config_ios_e6d2ed559f32c182ac8412737f5fb36a.o)
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in firebase(app_ios_814e1620d4f88024cea4bade26623a67.o)
  "_OBJC_CLASS_$_FIRAnalytics", referenced from:
      objc-class-ref in libfirebase_analytics.a(analytics_ios_d28a0e676a7367b8f2d91944bb505d87.o)
  "_FIRRemoteConfigThrottledEndTimeInSecondsKey", referenced from:
      ____ZN8firebase13remote_config5FetchEy_block_invoke in firebase_remote_config(remote_config_ios_e6d2ed559f32c182ac8412737f5fb36a.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by crazyhappygame** [comment]
@dantti This is exactly the same issue described in: https://stackoverflow.com/questions/51646982/qt-firebase-c-sdk-linking-issues-on-ios

**Comment by dantti** [comment]
if your try with CMake gave the same link error then I have no idea of what else to try...

**Comment by frankosterfeld** [comment]
You might miss the native FirebaseIOS libs which the firebase-cpp-sdk wraps. I also had to tell QMake `LIBS += -ObjC` to make it link the objective C libs properly, otherwise app (or storage?) initialization failed at runtime.

**Comment by dantti** [comment]
Thanks, I've put the app on hold, as I have another more important ATM, but probably next week I'll try, I didn't know the cpp sdk was a wrap around the Firebase IOS libs, I think this is a bit confusing due "supported" way being using cocoa pods..

**Comment by patm1987** [comment]
Hi @crazyhappygame,

I'm poking around a little at your issue, and just want to ask a few more questions if possible.

It looks like you're following the instructions on https://firebase.google.com/docs/ios/setup#frameworks, but only using the firebase-cpp SDK. The former actually links to this additional zip file to pull down: https://firebase.google.com/download/ios

I will say that, without seeing your entire CMakeLists.txt I may be making incorrect assumptions, so thank you for your patience if I say something totally out of left field.

First, I don't see any `-framework` calls as mentioned here: https://stackoverflow.com/questions/27585896/how-to-use-framework-using-cmake, although this may just work for system dependencies. The frameworks included in the download link I provided above includes a lot of the native hooks required by Firebase to integrate well with iOS. If you don't wish to use cocoapods, you should pull in the native iOS framework dependencies in whichever way your build pipeline permits.

I'm assuming that the plugins you want are Remote Config and Analytics. If you're following the iOS instructions for not using cocoapods, the Readme.md lists:
```
## RemoteConfig (~> Analytics)
- FirebaseABTesting.framework
- FirebaseRemoteConfig.framework
- Protobuf.framework
```

and
```
## Analytics
- FIRAnalyticsConnector.framework
- FirebaseAnalytics.framework
- FirebaseCore.framework
- FirebaseCoreDiagnostics.framework
- FirebaseInstanceID.framework
- GoogleAppMeasurement.framework
- GoogleDataTransport.framework
- GoogleDataTransportCCTSupport.framework
- GoogleUtilities.framework
- nanopb.framework
```
as the frameworks you'll need.

Once you have all of those, the C++ SDK should function correctly on iOS. These are a lot of dependencies, which is why cocoapods is so handy in this case.

I'm sure you've found it, but there is a good example project here: https://github.com/firebase/quickstart-cpp/tree/master/remote_config/testapp
It does use CocoaPods to manage the dependencies I listed above, but it might shed some light on how to setup a C++ project on iOS

Let me know if that helps at all,
--Patrick

**Comment by crazyhappygame** [comment]
@patm1987 thank you for explanation. It was really helpful!
Finally I successfully build my project with CMake only.

In deed linker error are because I did not link against libraries from:
https://firebase.google.com/download/ios

@dantti you have additionally download https://firebase.google.com/download/ios and link proper frameworks.

@stewartmiles I think that below section should be updated:
https://github.com/firebase/firebase-cpp-sdk/blob/master/README.md#including-in-projects
