### ISSUE TITLE
Clarify intended usage of the C++ SDK

### ISSUE THREAD

**Issue by cbenhagen** [firebase/firebase-cpp-sdk#42]
I am investigating possible solutions to add [Linux and Windows](https://github.com/FirebaseExtended/flutterfire/issues/2028) support to the [Flutter Firebase plugins](https://github.com/FirebaseExtended/flutterfire). Aside from a pure Dart implementation, the C++ SDK seems like a good base for this effort. Concerns were raised though that it's an SDK for testing mobile games on desktop, rather than a desktop SDK. Can you please clarify?

**Comment by morganchen12** [comment]
Hey @cbenhagen, many of the SDKs are C++ wrappers around their native counterparts, and thus are limited in their platform support since they cannot support platforms that do not have native SDKs available. Some of the desktop SDKs are stub implementations for testing as you mentioned.

The C++ SDK is currently best suited for developing cross-platform mobile games, but in the future we hope to extend support to desktop as well.

**Comment by cbenhagen** [comment]
@morganchen12 thank you for the super fast response! Pure Dart implementations might be the way to go then.
