### ISSUE TITLE
Support for maximum timeout for connection retry.

### ISSUE THREAD

**Issue by hbgxsm95** [firebase/firebase-cpp-sdk#47]
### Please fill in the following fields:
Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo:
Firebase C++ SDK version: 
Firebase plugins in use (Auth, Database, etc.):
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the C++ SDK on (Mac, Windows, or Linux): 
Platform you are targeting (iOS, Android, and/or desktop): 

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

Code to repro:

```cpp
settings.set_persistence_enabled(false);
settings.set_host("Invalid gcp oneplatform host url");

Future<DocumentReference> doc_ref =
      db->Collection("users").Add({{"first", FieldValue::FromString("Ada")},
                                   {"last", FieldValue::FromString("Lovelace")},
                                   {"born", FieldValue::FromInteger(1815)}});
while(doc_ref.status() != firebase::kFutureStatusComplete) {
  absl::SleepFor(absl::Seconds(5));
  LOG(INFO) << "HAHA?";
}
// Never reach here.
```

Firestore SDK supports retry and exponential backoff when it fails to connect the backend. However, there is no limit on the total retry times or timeout.  So when there is something wrong with the server side, e.g. backend is down, the end user will hang forever for the future completion callback. And this could cause OOM in the client side because client might keep adding more operations and callbacks. Could we set up a maximum retry timeout?

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ?

What's the issue repro rate? (eg 100%, 1/5 etc) 100%

**Comment by wu-hui** [comment]
Hi hbgxsm95,

Thanks for trying our CPP SDK and report this issue!

The returned `Future` will complete when the backend acknowledges the change (accept or reject). The call to `Set` returns means the change is captured in local storage (or memory if you have persistence:false). 

You'd want to wait for the completion if the write is critical and you want to be sure the backend has committed the change (a financial change, for example). 

Your App can proceed though, if you can accept that the change is saved in a local storage/memory. In this case you don't need to wait for the future to complete. Note, with persistence:false, and if your App restarts, the save change will be lost.

Regarding your OOM concern, by default the changes are saved to disk unless you set persistence:false, in that case the risk of OOM is not greatly higher if App is offline because all cache is in memory regardless.

Please let me know if I did my job of explanation well, and if you have further questions.
