### ISSUE TITLE
[Bug] getting compile error after put the newest FirebaseAnalytics SDK on iOS

### ISSUE THREAD

**Issue by jdcdj123** [firebase/firebase-cpp-sdk#971]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: (https://github.com/firebase/firebase-ios-sdk/releases/tag/9.1.0)
  * Firebase C++ SDK version: 9.1.0
  * Problematic Firebase Component: FirebaseAnalytics (Auth, Database, etc.)
  * Other Firebase Components in use: Crashlytics, Google-Mobile-Ads-SDK (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

I was using Firebase SDK 8.12.0 and tried to bump up the SDK version to 9.1.0
So I copied and paste the whole SDKs and getting the error saying

Undefined symbols for architecture arm64:
  "_APMUserDataFieldEmailAddress", referenced from:
      +[FIRAnalytics initiateOnDeviceConversionMeasurementWithEmailAddress:] in FirebaseAnalytics(FIRAnalytics.o)

SDKs list in XCode,
Firebaseanalytics
FirebaseCore
FirebaseCoreDiagnostics
FirebaseCoreInternal
FirebaseCrashlytics
FirebaseIntallations
GoogleDataTransport
PromisesObjC
GoogleAppMeasurement
GoogleAppMeasurementIdentitySupport
GoogleMobileAds
GoogleUtilities
nanopb
PromisesObjC
UserMessagingPlatform

am I missing something to add?

#### Steps to reproduce:

Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ?
What's the issue repro rate? (eg 100%, 1/5 etc) - 100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by AlmostMatt** [comment]
Hello.
You mention both C++ and iOS SDK in your post. Can you confirm whether your project is using the C++ SDK or if it is integrated with the native iOS SDK directly?
I ask because you mention version 9.1.0 in your post, and version 9.1.0 of the C++ SDK was not released at the time of your post, and it sounds like your error might be coming from the iOS SDK.

if you are using the iOS SDK directly, you might want to post the issue at https://github.com/firebase/firebase-ios-sdk

If you are using the C++ SDK, could you give a bit more info about what version of it you are using and whether you built from source?
